### ISSUE TITLE
Deze code werkt niet

### ISSUE THREAD

**Issue by hiddebraun-ma** [KevinKranenburg/OOP#2]
Wil je dit oplossen? de classes zouden bijvoorbeeld in losse folders moeten staan e.d.
Belangrijk onderdeel van dit vak is ook code organisatie en werkende code opleveren en inleveren!

De live url doet het wel, maar ik wil dus ook de code zien die er achter zit.

**Comment by KevinKranenburg** [comment]
Organisatie van code verbeterd.
